"""Remove default from owner_id

Revision ID: 055d5c111568
Revises: 80f463a5ae41
Create Date: 2025-06-12 07:47:43.782592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055d5c111568'
down_revision: Union[str, None] = '80f463a5ae41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'owner_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'owner_id', server_default='1')
    # ### end Alembic commands ###
